import type { Product } from './types'

// Product line from Ali's DETOX PLUS + vision document.
// Colors approximate the bottle liquids/labels in the renders.

export const PRODUCTS: Product[] = [
  // ---- Cold pressed juices (500 ml) ----
  {
    id: 'green-detox',
    name: 'Green Detox',
    category: 'juice',
    priceCents: 14990,
    color: '#4a7c2f',
    colorSoft: '#7fb069',
    benefits: { detox: 1, digestion: 0.6, skin: 0.4, hydration: 0.3 },
    tags: ['vegan'],
    blurb: {
      tr: 'Ispanak, salatalık, elma ve limonlu yeşil arınma.',
      en: 'Spinach, cucumber, apple and lemon green cleanse.',
    },
  },
  {
    id: 'immune-boost',
    name: 'Immune Boost',
    category: 'juice',
    priceCents: 14990,
    color: '#e8871e',
    colorSoft: '#f6b26b',
    benefits: { immunity: 1, energy: 0.5, skin: 0.3 },
    tags: ['vegan'],
    blurb: {
      tr: 'Portakal, havuç ve zencefil ile bağışıklık desteği.',
      en: 'Orange, carrot and ginger immunity support.',
    },
  },
  {
    id: 'red-detox',
    name: 'Red Detox',
    category: 'juice',
    priceCents: 14990,
    color: '#8e2043',
    colorSoft: '#c04a6b',
    benefits: { energy: 0.7, detox: 0.7, hydration: 0.3, calm: 0.2 },
    tags: ['vegan'],
    blurb: {
      tr: 'Pancar, nar ve kırmızı meyvelerle doğal güç.',
      en: 'Beetroot, pomegranate and red berries natural power.',
    },
  },
  {
    id: 'lemon-ginger',
    name: 'Lemon Ginger',
    category: 'juice',
    priceCents: 14990,
    color: '#f2c53d',
    colorSoft: '#f8dd85',
    benefits: { hydration: 0.9, immunity: 0.5, digestion: 0.4, energy: 0.3 },
    tags: ['vegan'],
    blurb: {
      tr: 'Limon, zencefil ve nane ile ferahlatıcı içim.',
      en: 'Refreshing lemon, ginger and mint.',
    },
  },

  // ---- Cold pressed shots (60 ml) ----
  {
    id: 'shot-celery-glow',
    name: 'Celery Glow Shot',
    category: 'shot',
    priceCents: 9990,
    color: '#7fb069',
    colorSoft: '#a8cf8e',
    benefits: { skin: 0.9, hydration: 0.6, detox: 0.4 },
    tags: ['vegan'],
    blurb: { tr: 'Kereviz özü ile cilt parlaklığı.', en: 'Celery pressed for skin glow.' },
  },
  {
    id: 'shot-oatmeal-ginger',
    name: 'Oatmeal Ginger Rise',
    category: 'shot',
    priceCents: 9990,
    color: '#d9b382',
    colorSoft: '#ecd3ae',
    benefits: { energy: 0.7, digestion: 0.7, protein: 0.3 },
    tags: ['vegan'],
    blurb: { tr: 'Yulaf ve zencefille güne başlangıç.', en: 'Oat and ginger morning rise.' },
  },
  {
    id: 'shot-turmeric-defense',
    name: 'Turmeric Defense',
    category: 'shot',
    priceCents: 9990,
    color: '#e3a008',
    colorSoft: '#f3c95c',
    benefits: { immunity: 1, calm: 0.3 },
    tags: ['vegan'],
    blurb: { tr: 'Zerdeçal ve karabiberle savunma.', en: 'Turmeric and black pepper defense.' },
  },
  {
    id: 'shot-wheatgrass-cleanse',
    name: 'Wheatgrass Cleanse',
    category: 'shot',
    priceCents: 9990,
    color: '#3f7d20',
    colorSoft: '#6faf4b',
    benefits: { detox: 1, digestion: 0.4 },
    tags: ['vegan'],
    blurb: { tr: 'Buğday çimi ile derin arınma.', en: 'Deep cleanse with wheatgrass.' },
  },
  {
    id: 'shot-beetroot-energy',
    name: 'Beetroot Energy',
    category: 'shot',
    priceCents: 9990,
    color: '#a4193d',
    colorSoft: '#d1517a',
    benefits: { energy: 1, hydration: 0.2 },
    tags: ['vegan'],
    blurb: { tr: 'Pancar ile doğal enerji patlaması.', en: 'Natural energy burst from beetroot.' },
  },
  {
    id: 'shot-acai-antiox',
    name: 'Açaí Antiox',
    category: 'shot',
    priceCents: 9990,
    color: '#5b2a86',
    colorSoft: '#8d5bb8',
    benefits: { skin: 0.7, immunity: 0.5, detox: 0.4 },
    tags: ['vegan'],
    blurb: { tr: 'Açaí ile antioksidan bakım.', en: 'Antioxidant care with açaí.' },
  },
  {
    id: 'shot-coconut-lime',
    name: 'Coconut Lime Hydrate',
    category: 'shot',
    priceCents: 9990,
    color: '#dfe8dc',
    colorSoft: '#f2f7f0',
    benefits: { hydration: 1, calm: 0.3 },
    tags: ['vegan'],
    blurb: { tr: 'Hindistan cevizi suyu ile derin nem.', en: 'Deep hydration with coconut water.' },
  },
  {
    id: 'shot-berry-bliss',
    name: 'Berry Bliss Shot',
    category: 'shot',
    priceCents: 9990,
    color: '#b03060',
    colorSoft: '#d76d95',
    benefits: { calm: 0.8, skin: 0.5 },
    tags: ['vegan'],
    blurb: { tr: 'Orman meyveleri ile keyifli mola.', en: 'A joyful berry moment.' },
  },
  {
    id: 'shot-mango-turmeric',
    name: 'Mango Turmeric Sun',
    category: 'shot',
    priceCents: 9990,
    color: '#f0a202',
    colorSoft: '#f9c95e',
    benefits: { energy: 0.6, immunity: 0.6, skin: 0.3 },
    tags: ['vegan'],
    blurb: { tr: 'Mango ve zerdeçal ile güneşli enerji.', en: 'Sunny energy of mango and turmeric.' },
  },
  {
    id: 'shot-charcoal-cleanse',
    name: 'Activated Charcoal Cleanse',
    category: 'shot',
    priceCents: 9990,
    color: '#2b2b2b',
    colorSoft: '#5a5a5a',
    benefits: { detox: 0.9, digestion: 0.5 },
    tags: ['vegan'],
    blurb: { tr: 'Aktif kömür ile güçlü arınma.', en: 'Powerful cleanse with activated charcoal.' },
  },
  {
    id: 'shot-spirulina-detox',
    name: 'Spirulina Detox',
    category: 'shot',
    priceCents: 9990,
    color: '#0f3d3e',
    colorSoft: '#2d6e70',
    benefits: { detox: 0.8, protein: 0.5, energy: 0.3 },
    tags: ['vegan'],
    blurb: { tr: 'Spirulina ile yeşil güç.', en: 'Green power of spirulina.' },
  },

  // ---- Probiotic yogurts ----
  {
    id: 'yogurt-organic',
    name: 'Organic Yogurt',
    category: 'yogurt',
    priceCents: 9990,
    color: '#f5f2ea',
    colorSoft: '#ffffff',
    benefits: { digestion: 1, protein: 0.7, calm: 0.3 },
    tags: ['dairy'],
    blurb: { tr: 'Organik süt, probiyotik, canlı kültür.', en: 'Organic milk, probiotic, live culture.' },
  },
  {
    id: 'yogurt-strawberry',
    name: 'Strawberry Yogurt',
    category: 'yogurt',
    priceCents: 9990,
    color: '#d16d7a',
    colorSoft: '#eaa9b2',
    benefits: { digestion: 0.8, protein: 0.6, skin: 0.3 },
    tags: ['dairy'],
    blurb: { tr: 'Çilekli probiyotik yoğurt.', en: 'Strawberry probiotic yogurt.' },
  },
  {
    id: 'yogurt-blueberry',
    name: 'Blueberry Yogurt',
    category: 'yogurt',
    priceCents: 9990,
    color: '#7d6b9e',
    colorSoft: '#a99bc4',
    benefits: { digestion: 0.8, protein: 0.6, calm: 0.4 },
    tags: ['dairy'],
    blurb: { tr: 'Yaban mersinli probiyotik yoğurt.', en: 'Blueberry probiotic yogurt.' },
  },
  {
    id: 'yogurt-mango',
    name: 'Mango Yogurt',
    category: 'yogurt',
    priceCents: 9990,
    color: '#e9b44c',
    colorSoft: '#f4d189',
    benefits: { digestion: 0.8, protein: 0.6, energy: 0.3 },
    tags: ['dairy'],
    blurb: { tr: 'Mangolu probiyotik yoğurt.', en: 'Mango probiotic yogurt.' },
  },
  {
    id: 'yogurt-chia',
    name: 'Chia Yogurt',
    category: 'yogurt',
    priceCents: 9990,
    color: '#9aa5a1',
    colorSoft: '#c3cbc8',
    benefits: { digestion: 0.9, protein: 0.8, hydration: 0.3 },
    tags: ['dairy'],
    blurb: { tr: 'Chia tohumlu probiyotik yoğurt.', en: 'Chia seed probiotic yogurt.' },
  },

  // ---- Fresh fruit (shelf bins — displayed with price plaques) ----
  {
    id: 'fruit-lemon',
    name: 'Lemon',
    category: 'fruit',
    priceCents: 2990,
    color: '#f7d54d',
    colorSoft: '#fbe98f',
    benefits: { immunity: 0.5, hydration: 0.3 },
    tags: ['vegan'],
    blurb: { tr: 'Taze limon.', en: 'Fresh lemon.' },
  },
  {
    id: 'fruit-lime',
    name: 'Lime',
    category: 'fruit',
    priceCents: 2990,
    color: '#8fbf4d',
    colorSoft: '#b8dc85',
    benefits: { immunity: 0.4, hydration: 0.3 },
    tags: ['vegan'],
    blurb: { tr: 'Taze misket limonu.', en: 'Fresh lime.' },
  },
  {
    id: 'fruit-apple',
    name: 'Red Apple',
    category: 'fruit',
    priceCents: 2990,
    color: '#c94f4f',
    colorSoft: '#e08b8b',
    benefits: { digestion: 0.4, energy: 0.3 },
    tags: ['vegan'],
    blurb: { tr: 'Taze kırmızı elma.', en: 'Fresh red apple.' },
  },
  {
    id: 'fruit-banana',
    name: 'Banana',
    category: 'fruit',
    priceCents: 2990,
    color: '#f2d13e',
    colorSoft: '#f8e587',
    benefits: { energy: 0.5, digestion: 0.3 },
    tags: ['vegan'],
    blurb: { tr: 'Taze muz.', en: 'Fresh banana.' },
  },
]

export const byId = (id: string): Product | undefined => PRODUCTS.find((p) => p.id === id)

// Turkish Lira, comma decimals — matches the shelf tags on the machine art
export const formatPrice = (cents: number): string => `₺${Math.floor(cents / 100)},${String(cents % 100).padStart(2, '0')}`
