import type { Localized, ReasonCode } from './types'

export const REASON_COPY: Record<ReasonCode, Localized> = {
  'goal-energy': { tr: 'Enerji hedefinle birebir uyumlu', en: 'Matches your energy goal' },
  'goal-immunity': { tr: 'Bağışıklık hedefini destekliyor', en: 'Supports your immunity goal' },
  'goal-detox': { tr: 'Arınma hedefin için ideal', en: 'Ideal for your detox goal' },
  'goal-skin': { tr: 'Cilt sağlığı hedefine katkı sağlıyor', en: 'Contributes to your skin goal' },
  'goal-digestion': { tr: 'Sindirim hedefini destekliyor', en: 'Supports your digestion goal' },
  'goal-hydration': { tr: 'Nem dengesi hedefine uygun', en: 'Fits your hydration goal' },
  'goal-calm': { tr: 'Sakinlik hedefine iyi geliyor', en: 'Good for your calm goal' },
  'self-energy': { tr: 'Bugün düşük enerjini toparlamak için', en: 'To lift your low energy today' },
  'self-sleep': { tr: 'Az uyuduğun için dengeleyici seçim', en: 'A balancing pick after little sleep' },
  'self-hydration': { tr: 'Az su içtiğin için nem takviyesi', en: 'Hydration support for a low-water day' },
  'scan-skin': { tr: 'Tarama: cilt görünümüne destek olabilir', en: 'Scan: may support your skin appearance' },
  'scan-hydration': { tr: 'Tarama: nem göstergen düşük görünüyor', en: 'Scan: your hydration indicator looks low' },
  'mood-happy': { tr: 'O ışıltıyı korumak için', en: 'Keeps that glow going' },
  'mood-sad': { tr: 'Yüzünü güldürmek için seçildi', en: 'Picked to turn that frown upside down' },
  'mood-tired': { tr: 'Yorgun gözlere doğal yakıt', en: 'Natural fuel for those sleepy eyes' },
  'mood-stressed': { tr: 'Kaşlarındaki düğümü çözmek için', en: 'Chosen to unknot that brow' },
  'weather-hot': { tr: 'Bu sıcakta içilebilir klima', en: 'Cools you down on a hot day' },
  'weather-cold': { tr: 'Soğuk güne karşı kalkan', en: 'Cold-day armor, bottled' },
  'weather-rainy': { tr: 'Yağmurlu güne iyi gelir', en: 'Comfort for a rainy day' },
  'weather-sunny': { tr: 'Güneşli gün onaylı seçim', en: 'A sunshine-approved pick' },
  'time-morning': { tr: 'Güne parlak bir başlangıç', en: 'A bright way to start the day' },
  'time-evening': { tr: 'Günü tatlı tatlı kapatır', en: 'Winds the day down gently' },
  'season-winter': { tr: 'Kış bağışıklık desteği', en: 'Winter immunity backup' },
  'season-spring': { tr: 'Bahara taze bir başlangıç', en: 'A fresh-start spring cleanse' },
  'season-summer': { tr: 'Yaz sıcağı için birebir', en: 'Made for summer heat' },
  'season-autumn': { tr: 'Sonbahar savunması, şişede', en: 'Autumn defense, bottled' },
  'diet-ok': { tr: 'Beslenme tercihlerinle uyumlu', en: 'Compatible with your dietary choices' },
}
